# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-05 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190105_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='faculty',
            field=models.CharField(choices=[('engineering', 'ENNGINEERING'), ('science', 'SCIENCE'), ('commerce', 'COMMERCE'), ('humanity', 'HUMANITY')], max_length=30, null=True, verbose_name='faculty'),
        ),
    ]
