# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-10 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_myuser_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='faculty',
            field=models.CharField(max_length=30, null=True, verbose_name='faculty'),
        ),
    ]
