# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-14 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190114_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=30, verbose_name='user name'),
        ),
    ]
