# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-17 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190114_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='macid',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='macid'),
        ),
    ]
