# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-17 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_myuser_macid'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='lable',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True, verbose_name='lable'),
        ),
    ]
