# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-21 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0012_collectlog_filename'),
        ('accounts', '0008_myuser_lable'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='score',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='datacollection.file_score'),
            preserve_default=False,
        ),
    ]
