# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-21 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_myuser_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='lable',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='lable'),
        ),
    ]
