# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-23 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190120_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='Score'),
        ),
    ]
