# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-23 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190122_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='score',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Score'),
        ),
    ]
