# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-10 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190123_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='user name'),
        ),
    ]
