# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-12 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20190210_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='faculty',
            field=models.CharField(choices=[('Engineering', 'ENGINEERING'), ('Arts & Science', 'ARTS & SCIENCE'), ('Commerce', 'COMMERCE'), ('Humanities', 'HUMANITIES'), ('Social Sciences', 'SOCIAL SCIENCES'), ('Science', 'SCIENCE'), ('Health Sciences', 'HEALTH SCIENCES')], max_length=30, null=True, verbose_name='faculty'),
        ),
    ]
