# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-05 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pathmagfp',
        ),
        migrations.DeleteModel(
            name='Pathwififp',
        ),
        migrations.DeleteModel(
            name='Pointmagfp',
        ),
        migrations.DeleteModel(
            name='Pointwififp',
        ),
    ]
