# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-19 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datacollection', '0002_auto_20190105_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='collectlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MacID', models.CharField(max_length=30, null=True, verbose_name='MacID')),
                ('Mode', models.IntegerField(blank=True, max_length=30, null=True, unique=True, verbose_name='Mode')),
            ],
        ),
    ]
