# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-19 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0003_collectlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectlog',
            old_name='id',
            new_name='ID',
        ),
        migrations.AddField(
            model_name='collectlog',
            name='Duration',
            field=models.CharField(max_length=30, null=True, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='collectlog',
            name='Start_Lat',
            field=models.FloatField(null=True, verbose_name='Start_Lat'),
        ),
        migrations.AddField(
            model_name='collectlog',
            name='Start_Lon',
            field=models.FloatField(null=True, verbose_name='Start_Lon'),
        ),
        migrations.AddField(
            model_name='collectlog',
            name='Terminal_Lat',
            field=models.FloatField(null=True, verbose_name='Terminal_Lat'),
        ),
        migrations.AddField(
            model_name='collectlog',
            name='Terminal_Lon',
            field=models.FloatField(null=True, verbose_name='Terminal_Lon'),
        ),
        migrations.AddField(
            model_name='collectlog',
            name='Time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='collectlog',
            name='Mode',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Mode'),
        ),
    ]
