# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-19 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0004_auto_20190118_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectlog',
            name='Building',
            field=models.CharField(max_length=30, null=True, verbose_name='Building'),
        ),
        migrations.AddField(
            model_name='collectlog',
            name='Errorcode',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Errorcode'),
        ),
        migrations.AddField(
            model_name='collectlog',
            name='Filename',
            field=models.CharField(max_length=125, null=True, verbose_name='Filename'),
        ),
        migrations.AddField(
            model_name='collectlog',
            name='Floor',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Floor'),
        ),
        migrations.AddField(
            model_name='collectlog',
            name='Room',
            field=models.CharField(max_length=30, null=True, verbose_name='Room'),
        ),
    ]
