# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-19 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0005_auto_20190118_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Filename', models.CharField(max_length=125, null=True, verbose_name='Filename')),
                ('Score', models.FloatField(null=True, verbose_name='Score')),
            ],
        ),
    ]
