# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-20 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0006_file_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectlog',
            name='Floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Floor'),
        ),
    ]
