# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-20 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0008_auto_20190120_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectlog',
            name='Mode',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mode'),
        ),
    ]
