# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-21 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0010_auto_20190120_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectlog',
            name='Filename',
        ),
    ]
