# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-29 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0012_collectlog_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='taskitem',
            fields=[
                ('ID', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Building', models.CharField(max_length=30, null=True, verbose_name='Building')),
                ('Floor', models.IntegerField(blank=True, null=True, verbose_name='Floor')),
                ('Scale', models.FloatField(default=1.0, verbose_name='Scale')),
                ('Createtime', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Createtime')),
                ('Resttime', models.FloatField(default=30.0, verbose_name='Resttime')),
                ('MacID', models.CharField(max_length=30, null=True, verbose_name='MacID')),
                ('Accepttime', models.DateTimeField(blank=True, null=True, verbose_name='Accepttime')),
                ('Expiretime', models.DateTimeField(blank=True, null=True, verbose_name='Expiretime')),
            ],
        ),
    ]
