# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-12 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0013_taskitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectlog',
            name='Filename',
            field=models.CharField(max_length=125, null=True, verbose_name='Filename'),
        ),
    ]
